### ISSUE TITLE
package download

### ISSUE THREAD

**Issue by DICAP1** [tg12/FAIG#22]
I am using a mac and thus OSX.  
Pycharm is my IDE for Python 3.6. I cant seem to find the following packages

pygobject==3.24.1
python-apt==1.4.0b3'

Intall fails with error

Any help?

**Comment by tg12** [comment]
You should not need these packages actually, They get installed as pre reqs as other packages. The main ones are Numpy, Pandas, Requests. Hope that helps. It is not version specific infact it would be better to use the latest version for each package.

**Comment by DICAP1** [comment]
Hi

Thank you for coming back to me so swiftly


Other than the packages, I am inputing the API Key I have generated , swells my username and password 

Is this all I need do before running?  I am only 1 month into learning python so, apologies if questions are simple
Charles

**Comment by tg12** [comment]
That's right! No problem at all. Enjoy.

**Comment by mrvbwiz** [comment]
Yes,  am keen to get this working and add a few bits too.   Where in the config in pycharm do I add the api key?

**Comment by tg12** [comment]
Nowhere in pycharm. Just in default.conf.

**Comment by DICAP1** [comment]
Hi

Your code says not to set it here but in config.conf
Should I replace the Asterix with the key?




Charles Glah. ASIP
Founder
Divergence Capital Ltd
Social Impact Investing

Divergencecapital.com

**Comment by tg12** [comment]
Yes sorry, config.conf. Set it in there. Yes replace those

**Comment by DICAP1** [comment]
Ok so no need to create a new file called config.conf and copy details from default config as suggested?

**Comment by DICAP1** [comment]
Ok I added the key and get the following error when I runt he file faig

**Comment by tg12** [comment]
What was the error?

**Comment by DICAP1** [comment]
Error message

**Comment by tg12** [comment]
I cant see anything attached.

**Comment by DICAP1** [comment]
/usr/local/bin/python3.6 /Users/charlesglah/FAIG-master/faig.py
Traceback (most recent call last):
  File "/Users/charlesglah/FAIG-master/faig.py", line 9, in <module>
    api = API()
  File "/Users/charlesglah/FAIG-master/ig.py", line 27, in __init__
    d = super().session()
  File "/Users/charlesglah/FAIG-master/igclient.py", line 26, in wrap
    return f(*args, **kwargs)
  File "/Users/charlesglah/FAIG-master/igclient.py", line 73, in session
    self.auth[h] = headers_json[h]
KeyError: 'CST'

Process finished with exit code 1

**Comment by tg12** [comment]
OK, CST error is nearly always a problem on the IG Index side, So things like Incorrect password/ mis match between DEMO and LIVE API keys. I would ask further on the Discord. This has come up alot of times before.

**Comment by DICAP1** [comment]
Ok I will contact IG

I have created a copy of the default.conf file called config.conf, as you suggest din the notes.

It is there I have added the USERNAME and Password and API Key

Is this correct?

Need I do anything else prior to running?

Charles

**Comment by mrvbwiz** [comment]
Ok, I see.  It appears I mixed up demo with live account.  It seems I am using live account credential and I generated the API key when I live account.
I commented out the wring end point url and all seems to be working now

I see output.

What is the workflow?
Where are the predictions from linear regression?

What does this output all me?  Is it searching for a trade?

**Comment by DICAP1** [comment]
YES, how do I interpret this?
What is the linear regression prediction?
What is the workflow?

CS.D.sp_USDRUB.TODAY.IP: Price change 0.45%
CS.D.AUDGBP.TODAY.IP: Price change 0.23%
CS.D.USDTWD.TODAY.IP: Price change 0.35%
CS.D.GBPZAR.TODAY.IP Day Price Change 1.85% :- spread not ok -200.00<=-2.00
CS.D.GBPTRY.TODAY.IP Day Price Change -0.61% :- spread not ok -70.00<=-2.00
CS.D.SGDJPY.TODAY.IP: Price change -0.29%
CS.D.AUDSGD.TODAY.IP: Price change 0.32%
CS.D.USDMXN.TODAY.IP Day Price Change 0.76% :- spread not ok -50.00<=-2.00
CS.D.GBPPLN.TODAY.IP: Price change 0.27%
CS.D.USDMYR.TODAY.IP: Price change 0.01%
CS.D.USDCAD.TODAY.IP: Price change 0.35%
CS.D.NZDEUR.TODAY.IP: Price change 0.21%
CS.D.USDNOK.TODAY.IP: Price change 0.07%
CS.D.AUDUSD.TODAY.IP: Price change 0.05%
CS.D.USDSGD.TODAY.IP: Price change 0.27%
sleeping for 30s, since we've hit the end of the epic list
CS.D.CHFJPY.TODAY.IP: Price change -0.45%
CS.D.AUDCAD.TODAY.IP: Price change 0.41%
CS.D.EURCHF.TODAY.IP: Price change 0.17%
CS.D.CADNOK.TODAY.IP: Price change -0.27%
Charles Glah. ASIP
Founder
Divergence Capital Ltd
Social Impact Investing

Divergencecapital.com

**Comment by DICAP1** [comment]
Hi…further to my workflow question, what is the EPIC list?   Is this the list of all instruments the code is scanning?

If I only want to look at specific instruments can I do this?

**Comment by tg12** [comment]
Hi Charles, With all due respect if you are going to use this for commercial gain you should really be contributing back to the project somehow. Not that I am insisting you do but it's only fair. There are a handful of people who contributed code to this for nothing in return except for the good of the project. Whilst I do not have an issue with anyone using the code at all, After all I did release it. I cannot support this on a commercial basis. Nor should you be using it as basis for commercial enterprise (Ethically or technically). There are no guarantees of this. 

What do you mean by "workflow" exactly? 

Linear Regression is a standard formula used in a number of things, I suggest you do some further reading on this. 

https://en.wikipedia.org/wiki/Linear_regression

The version you are using there it is searching through all the Forex Currency Pairs. So yes it is searching for a trade. What is your level of trading knowledge? You seem to be founder of a trading company right? If you are you should know that the spread it and why it is important to get a low spread. 

Any reference to "epic" is IG's internal way of saying "ticker" as in Stock Ticker. They use epic to denote an instrument, Any trading instrument whether it be Forex, Stocks, or Commodities. In this version the EPIC list is not updated automatically, It is in other versions of the code. You can find them if you wish.

Good luck,, But any further support would have to be community based (Check the discord, However I expect you would be met with a frosty reception if you are using this for commercial gain as it is not intended this way) or if it is from me personally I will have to insist on a donation of good will.

**Comment by DICAP1** [comment]
Hi there

Thank you for the explanation

I have no plans to use this for commercial gain.  I am rather interested in data science, a use case for me to practice python.  

Yes I understand linear regression I was just wondering where the predicted price was output too.

My plan is to add a technical and fundamental analysis pattern recognition file to this code,

Thanks so much,

Charles

**Comment by tg12** [comment]
OK sure, No problem then. 

I would suggest you run it in DEMO first. Then you can see how it works. There is some debugging in there so you should be able to see where the variables exist. 

Good luck!

**Comment by DICAP1** [comment]
Thanks so much. I will explore.
