### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by DICAP1** [tg12/FAIG#23]
This code regularly times out.  What causes this and should I expect this.

**Comment by tg12** [comment]
This could be anything at all. What is your connection like to the ig servers? test the latency between the API Endpoints from your network. 

https://demo-api.ig.com/gateway/deal

https://api.ig.com/gateway/deal

**Comment by DICAP1** [comment]
Thank you.Its seems I cannot access these links 
-------- Original message --------From: tg12 <notifications@github.com> Date: 29/05/2019  11:25  (GMT+00:00) To: tg12/FAIG <FAIG@noreply.github.com> Cc: DICAP1 <charlesglah@divergencecapital.com>, Author <author@noreply.github.com> Subject: Re: [tg12/FAIG] Time out (#23) This could be anything at all. What is your connection like to the ig servers? test the latency between the API Endpoints from your network.
https://demo-api.ig.com/gateway/deal
https://api.ig.com/gateway/deal

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tg12/FAIG/issues/23?email_source=notifications\u0026email_token=ALKNZOAN63SDNFCMXRF2U43PXZK2FA5CNFSM4HQLI3VKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWO4MZA#issuecomment-496879204",
"url": "https://github.com/tg12/FAIG/issues/23?email_source=notifications\u0026email_token=ALKNZOAN63SDNFCMXRF2U43PXZK2FA5CNFSM4HQLI3VKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWO4MZA#issuecomment-496879204",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tg12** [comment]
Those are just the API endpoints, Test your latency against ...

demo-api.ig.com
api.ig.com

**Comment by tg12** [comment]
Further investigation required by user. Not necessarily related to code.
