### ISSUE TITLE
trade

### ISSUE THREAD

**Issue by DICAP1** [tg12/FAIG#25]
Why is no traded being posted

CS.D.NZDUSD.TODAY.IP Day Price Change -0.5% :- GOOD SPREAD -1.80>-2.00
No Trade This time
!!DEBUG shortPositionPercentage:57.0 longPositionPercentage:43.0 clientsentiment_value:69.0 hightrend_watermark:89.0

**Comment by tg12** [comment]
What trade were you expecting to see?

**Comment by DICAP1** [comment]
now resolved
