### ISSUE TITLE
not picking up trades

### ISSUE THREAD

**Issue by DICAP1** [tg12/FAIG#26]
Hi .   I have download the script, and i winder who i am not picking up any trading opportunities these past few days.

i have made no adjustments straight out of the box

What conditions van i tweak other than spread?
i want to add a pattern recognition algorithm base don price, and divergence.
When can this sit?

**Comment by tg12** [comment]
How much do you know about trading? I would first learn about trading alot before you run this. 

It might not pick up a trade for a while, There is a risk of over trading. 

This is issue with the code as such I will close them, The code is meant to be adapted to your own trading strategy and styles. It's really up to you to fit it to your risk profile. Trading discussions are best left for the Discord (Link on front page), People have different theory's on this.

IF you want to test this in demo, Reduce the predict_accuracy variable in the config file or increase the spread.

**Comment by DICAP1** [comment]
Hi

I know a fare bit about trading but still learning

Thanks for the direction.’

Charles.

**Comment by tg12** [comment]
Cool, Good luck. There is always the discord there if you need it. The code released is to automate trading, Not to pick trades for you. Sample algorithms are included but they are no means exhausted. I would check some of my other projects too. I have released some of my most profitable ones. I am working on the short trading but that is the most profitable I will not be releasing the code for this. I have given alot to the community and a good starting place for people to develop this further.

**Comment by DICAP1** [comment]
Thank you.  I will take a look for some of your other code too once I get my head around this one.

 Its all fascinating stuff.


Thank you so much
Charles

**Comment by DICAP1** [comment]
…btw if I only want to focus on specific pairs, do I merely just change the members of the epic list, and I already have a successful solution for picking pairs which I will share?

Charles
Charles Glah. ASIP
Founder
Divergence Capital Ltd
Social Impact Investing

Divergencecapital.com

**Comment by tg12** [comment]
Very much fascinating for me too. Thanks. I've been investing for over a decade. 

> do I merely just change the members of the epic list, and I already have a successful solution for picking pairs which I will share?

Absolutely.
