### ISSUE TITLE
Any idea for the Json serializable issue?

### ISSUE THREAD

**Issue by RonnSanji** [tg12/FAIG#31]
Tried to run faig.py but got the error below :

$ python faig.py 
Traceback (most recent call last):
  File "faig.py", line 9, in <module>
    api = API()
  File "/FAIG-master/ig.py", line 27, in __init__
    d = super().session()
  File "/FAIG-master/igclient.py", line 27, in wrap
    return f(*args, **kwargs)
  File "/FAIG-master/igclient.py", line 75, in session
    r = self._handlereq( requests.post(self.API_ENDPOINT + '/session', data=json.dumps(data), headers=self.session_headers) )
  File "/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable

**Comment by RobBickel** [comment]
The script error'd on login. Either you forgot to put in your credentials, or you don't have the right type of account at IG.

**Comment by tg12** [comment]
> The script error'd on login. Either you forgot to put in your credentials, or you don't have the right type of account at IG.

Most likely this.

**Comment by RonnSanji** [comment]
Got it... thanks .. will check the account again..

**Comment by RonnSanji** [comment]
> > The script error'd on login. Either you forgot to put in your credentials, or you don't have the right type of account at IG.
> 
> Most likely this.
Hi tg12, 

Thanks for the suggestion. The Json problem has been solved. Now, there is another issue. 
When I run the faig.py by using my demo account, the account information can be retrieved correctly however, it shows an warning below :

WARNING:root:Server error:ERROR
CS.D.CHFNOK.TODAY.IP: Price change 0.05% 

Seems the order is also not placed.  Any idea about this issue ?

**Comment by tg12** [comment]
That's a market issue not to do with this code. It's probably because it's not tradeable or you haven't got the required margin for that instrument.
