### ISSUE TITLE
Epic pricechange/spread error?

### ISSUE THREAD

**Issue by FlickeringIRoam** [tg12/FAIG#4]
https://github.com/tg12/FAIG/blob/3e577ec66a8fe92fe7da20f1a38a56e1fd16737f/faig.py#L203

is actually the same as:
`if Price_Change_Day_percent < -0.48 and Price_Change_Day_percent > -1.9:`

I don't necessarily know the logic behind it, but I suspect this should be:
`if (Price_Change_Day_percent > 0.48 and Price_Change_Day_percent < 1.9) or (Price_Change_Day_percent < -0.48 and Price_Change_Day_percent > -1.9):`
to pick up buys OR sells

If not, it can be simplified to the above 2 conditions.

**Comment by tg12** [comment]
As discussed, Think we have this one fixed.
