### ISSUE TITLE
Sample config files

### ISSUE THREAD

**Issue by ghost** [tg12/FAIG#6]
Would like to offer some help and at the same time learn something about FOREX.
Could sample config files (i.e. "default.conf" and "config.conf") be included in project?

**Comment by ghost** [comment]
Sorry, could be a stupid question.
Is "config.conf" just the renamed version of "default.conf"?

**Comment by tg12** [comment]
All the .conf needs is your Username/Password combo and your API key from IG Index. 

https://labs.ig.com/gettingstarted

Hope that helps. 

All the Epics are preset from all the Forex Pairs. And the b_contrarian flag is if you want to trade with or against the trend. As most retail traders are unsuccessful it is often advised to go against the trend.

**Comment by ghost** [comment]
Thanks, that definitely helps.
